export const metadata = {
  title: "About || Shariatpur-rent-a-car",
  description: "Generated by Shariatpur-rent-a-car",
};
const Aboutpage = () => {
  return <div>about</div>;
};

export default Aboutpage;
