import LoginForm from "@/components/LoginForm/LoginForm";
import Link from "next/link";
export const metadata = {
  title: "Login || Shariatpur-rent-a-car",
  description: "Generated by Shariatpur-rent-a-car",
};
const Loginpage = () => {
  return (
    <div>
      <LoginForm></LoginForm>
    </div>
  );
};

export default Loginpage;
