import Providers from "@/lib";
import "./globals.css";
import { DM_Serif_Display } from "next/font/google";
import NavBer from "@/components/Navber";

const DM_Serif = DM_Serif_Display({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Home || Shariatpur-rent-a-car",
  description: "Generated by Shariatpur-rent-a-car",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={DM_Serif.className}>
        <Providers>
          <div className="">
            <NavBer></NavBer>
            <div className=" md:min-h-[calc(100vh-100px)]">{children}</div>
            <div>footer</div>
          </div>
        </Providers>
      </body>
    </html>
  );
};
export default RootLayout;
