export const metadata = {
  title: "Services || Shariatpur-rent-a-car",
  description: "Generated by Shariatpur-rent-a-car",
};
const ServicesPage = () => {
  return <div>Services</div>;
};

export default ServicesPage;
