import SignUpForm from "@/components/SignUpForm/SignUpForm";
import Link from "next/link";
export const metadata = {
  title: "Sign Up || Shariatpur-rent-a-car",
  description: "Generated by Shariatpur-rent-a-car",
};
const signup = () => {
  return (
    <div>
      <SignUpForm></SignUpForm>
    </div>
  );
};

export default signup;
